### PR TITLE
Feature: allow to exclude properties from Gelf output

### PR DESCRIPTION
**Pull request by ghandmann**
This PR adds an publicly available `ExcludePropertyKeys`-Property in `IGelfConverterOptions`. Therefore it is now possible to add custom Propertie-Keys which shall be excluded when creating the Gelf JSON.

Reason: I am using the GelfLayout in some ASP.net core applications. And some of the ASP.net core built in log statements are includ a `MethodInfo` property in their logs. These statements exploded to up to 12mb in JSON and significantly require compute power to be generated. These `MethodInfo` properties dump all the currently loaded assemblies with ther PublicKey fingerprints, etc.

I have uploaded a full gzipped dump of such a message to [my webspace](https://sveneppler.de/stuff/GelfLayout-MethodInfo-Json-Log.txt.gz).

This can be "fixed" by setting `IncludeAllProperties=false`. But without this, there is no more structural logging possible. Only the log message and the fields defined by Gelf than arrive on the Graylog server.

Since i haven't found a way on how to filter out such a message on the ASP.net core/Microsoft.Extension.Logging side, i thought about filtering the field on the Gelf side.

With this PullRequest i just adopted the already existing (but private) `ExcludePropertyKeys` and added it to the `IGelfConverterOptions` interface. At least programatically it is now possible to provide property keys which are not serialized to Gelf output anymore. The old private `ExcludePropertyKeys` still exists, since it looks like you are filtering out all the fields that you re-generate anyway. So i have not mixed these.

Info about the newline changes: Your code base appears to have mixed line endings inside of files. Sadly my VS Code decides to force line endings for the entire file. Leading to a lot of changes only regarding line endings. That's way i seperated these changes in two commits (the change overview still shows them of course). But this should give you the option to alternatively cherry pick the fixing-commit.

Don't hesitate if i should change something. There is no CONTRIBUTING.md in your repo, so i just fired up this pull request at you. :)

### CODE REVIEW

**Comment by snakefoot** [comment]
Could the property be renamed from `ExcludePropertyKeys` to `ExcludeProperties ` ?

This would match the JsonLayout: https://github.com/nlog/nlog/wiki/JsonLayout

**Comment by snakefoot** [comment]
We could also consider to modify the Gelf.Layout to always perform ToString when meeting MethodInfo-objects. Ex. newer version of the JsonSerializer ensures to handle Exception.TargetSite without jumping into the sea.

**Comment by snakefoot** [comment]
Think you could add this converter to `CreateJsonSerializerSettings`:

```c#
            jsonSerializerSettings.Converters.Add(new ToStringConverter(typeof(System.Reflection.Assembly)));
            jsonSerializerSettings.Converters.Add(new ToStringConverter(typeof(System.Reflection.Module)));
            jsonSerializerSettings.Converters.Add(new ToStringConverter(typeof(System.Reflection.MethodInfo)));
```

```c#
        public class ToStringConverter : JsonConverter
        {
            private readonly Type _type;

            /// <inheritdoc />
            public override bool CanRead { get; } = false;

            public ToStringConverter(Type type)
            {
                _type = type;
            }

            /// <inheritdoc />
            public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    writer.WriteNull();
                }
                else
                {
                    writer.WriteValue(value.ToString());
                }
            }

            /// <inheritdoc />
            public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
            {
                throw new NotSupportedException("Only serialization is supported");
            }

            /// <inheritdoc />
            public override bool CanConvert(Type objectType)
            {
                return _type.IsAssignableFrom(objectType);
            }
        }
```

**Comment by ghandmann** [comment]
Oh indeed, i like the idea of plugging in special JsonConverters for desired types. Didn't think of that!

But how would i inject those settings into the GelfLayout? The only way i was able to spot easily would be to "pollute" the `JsonConvert.DefaultSettings` globally. But that feels a little bit hacky, since ASP.net Core (or any other lib) may wish to deserialize the `System.Reflection.MethodInfo` somewhere else down the line. By changing the `DeafultSettings` i would also interfere with these use cases, right?

**Comment by snakefoot** [comment]
I was thinking to add those 3 reflection-types by default in GelfLayout (They are dangerous as they will dump all known types in the applications).

Then you could have a HashSet  of Type-objects. That one can add extra, where it should always perform ToString.

Still think you should keep the ability to exclude property names (just rename property to match Jsonlayout)

**Comment by snakefoot** [comment]
Created PR #20 with support for ExcludedProperties and ignores System-Reflection-Types by default.

**Comment by SergeyKulgan** [comment]
Hi guys. I also need functionality to exclude specific columns. 
Can you merge this PR please?
@snakefoot , as I understand, you are expert here, also I have question:
is it possible to rename output GELF (including GELF-appended) columns? 
For example:
rename 'facility' to 'Facility' (because all our configured Graylog inputs and alert notification rules adjusted for 'Facility' and we want to keep all working and keep compatibility with tonnes of existing logs)

**Comment by snakefoot** [comment]
> is it possible to rename output GELF (including GELF-appended) columns?

Not with this Gelf Layout library. When looking at the example payloads then everything is lowercase. Think it is best that it stays that way:

https://docs.graylog.org/en/3.2/pages/gelf.html

But you can always make your own fork, and make the necessary changes.

Btw. you are high-jacking another persons PR to discuss you own issues. It is good practice to start new issue for a new discussion.

**Comment by SergeyKulgan** [comment]
@snakefoot , you are right. I understand, according to GELF documentation - all properties are lowercase. I just wanted to keep backward compatibility with our existing logic (poorly-written initially by some guys).

So, about excluding properties, my question still remain, when this PR will be merged and we will get new version?
For issues, not related to the PR - I'll open new issue, as you noticed.

**Comment by snakefoot** [comment]
> So, about excluding properties, my question still remain, when this PR will be merged and we will get new version?

Cannot answer that question. Btw. I have created PR #20 that extends the solution presented here.

Will probably make another PR to also support adding additional custom types to exclude from serialization. But small steps.

**Comment by tomikiss** [comment]
Hi all, I'm reviewing this as it stand would prefer #20. Will merge new version today.

**Comment by snakefoot** [comment]
@SergeyKulgan + @ghandmann An updated version is now available, that supports `ExcludeProperties`:

https://www.nuget.org/packages/NLog.GelfLayout

And it automatically skips system-reflection-types.

**Comment by tomikiss** [comment]
#20 has been merged which provide clean implementation of this feature request.

**Comment by ghandmann** [comment]
Just wanted to say sorry, for not reacting. I was in parental time and haven't looked into my github account. But i'm glad that the idea kicked off. :) :+1:

**Pull request closed without merging**
