### PR TITLE
Version 1.0

### PR DESCRIPTION
**Pull request by snakefoot**

### CODE REVIEW

**Comment by snakefoot** [comment]
@tomikiss Any chance this can be merged, and we can have a ver. 1.0 released ?

**Comment by snakefoot** [comment]
@tomikiss Polite poke for merge and release

**Comment by tomikiss** [comment]
Thanks for this contribution, releasing this today.

**Comment by snakefoot** [comment]
Thank you. Will start spreading the good word about the Gelf-Library that are better than most :)

**Comment by farzadpanahi** [comment]
tnx everyone for keeping this project alive and improving it : )

**Pull request merged**
