### PR TITLE
 GelfLayout - Supports ExtraFields and IncludeMdlc 

### PR DESCRIPTION
**Pull request by snakefoot**
Introduced GetlfLayout with support for adding extra fields:

```
	<target xsi:type="Network" name="GelfHttp" address="http://localhost:12201/gelf">
		<layout type="GelfLayout" facility="MyFacility">
			<field name="threadid" layout="${threadid}" />
		</layout>
	</target>
```

The following changes has also been made:
- Reduced allocations by writing message directly to `JsonTextWriter` (Skips allocation of  internal `GelfMessage`-object and `JObject`-object).
- Reduced allocations by writing custom fields directly to `JsonTextWriter` (Skips allocations of `JToken` for primitive types).
- Added support for NLog `ThreadSafe`-attribute for improved concurrency in async-mode.
- Added option `IncludeLegacyFields` so one can skip deprecated fields (according to GELF 1.1 spec)
- Added fallback to Logger-name, when CallSite FilePath is null / empty.

### CODE REVIEW

**Comment by snakefoot** [comment]
@tomikiss Hope this can be merged and released, as it will allow one to replace these packages:

https://github.com/infobip/NLog.Targets.Gelf
https://github.com/mparlak/NLog.AspNetCore.TargetGelf
https://github.com/GokGokalp/NLog.Web.AspNetCore.Targets.Gelf
https://github.com/dustinchilson/NLog.Targets.GraylogHttp

Later one might consider removing the `Newtonsoft.Json`-dependency and use the JsonSerializer included in NLog (See JsonLayout).

**Comment by snakefoot** [comment]
@gokhanabatay Would you mind trying out this custom build of [NLog.GelfLayout](https://www.nuget.org/packages/NLog.GelfLayout)-package (Reduces memory allocations):

[NLog.GelfLayout.0.4.0.nupkg.zip](https://github.com/farzadpanahi/NLog.GelfLayout/files/3483551/NLog.GelfLayout.0.4.0.nupkg.zip) - Remove `.zip` extension and place in local nuget folder.

It allows you to make use the NLog NetworkTarget like this:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog>
  <extensions>
    <add assembly="NLog.Web.AspNetCore" />
    <add assembly="NLog.Layouts.GelfLayout" />
  </extensions>
  <target xsi:type="Network" name="Graylog" address="udp://xxxxx">
    <layout xsi:type="GelfLayout" facility="BackEnd">
      <field name="AspnetRequestUrl" layout="${aspnet-request-url:IncludeHost=true:IncludePort=true}"/>
      <field name="AspnetRequestHost" layout="${aspnet-request-host}"/>
      <field name="AspnetRequestIp" layout="${aspnet-request-ip}"/>
      <field name="AspnetRequestReferrer" layout="${aspnet-request-referrer}"/>
      <field name="RequestGuid" layout="${mdc:item=RequestGuid}"/>
      <field name="Environment" layout="${gdc:item=Environment}"/>
      <field name="SessionId" layout="${mdc:item=SessionId}"/>
      <field name="UserId" layout="${mdc:item=UserId}"/>
      <field name="Channel" layout="${mdc:item=Channel}"/>
      <field name="ApplicationName" layout="${gdc:item=ApplicationName}"/>
      <field name="LogDate" layout="${longdate}"/>
      <field name="MethodName" layout="${event-properties:item=MethodName}"/>
      <field name="ElapsedMilliseconds" layout="${event-properties:item=ElapsedMilliseconds}"/>
      <field name="ExternalServiceUrl" layout="${event-properties:item=ExternalServiceUrl}"/>
    </layout>
  </target>
  <rules>
     <logger name="*" minlevel="Debug" writeTo="Graylog" />
  </rules>
</nlog>
```

You can also use tcp (allows you to write messages larger than 8 KByte), but you need to upgrade to NLog ver. 4.6.5 (Supports `lineEnding="Null"`):

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog>
  <extensions>
    <add assembly="NLog.Web.AspNetCore" />
    <add assembly="NLog.Layouts.GelfLayout" />
  </extensions>
  <target xsi:type="Network" name="Graylog" address="tcp://xxxxx" newLine="true" lineEnding="Null">
    <layout xsi:type="GelfLayout" facility="BackEnd">
      <field name="AspnetRequestUrl" layout="${aspnet-request-url:IncludeHost=true:IncludePort=true}"/>
      <field name="AspnetRequestHost" layout="${aspnet-request-host}"/>
      <field name="AspnetRequestIp" layout="${aspnet-request-ip}"/>
      <field name="AspnetRequestReferrer" layout="${aspnet-request-referrer}"/>
      <field name="RequestGuid" layout="${mdc:item=RequestGuid}"/>
      <field name="Environment" layout="${gdc:item=Environment}"/>
      <field name="SessionId" layout="${mdc:item=SessionId}"/>
      <field name="UserId" layout="${mdc:item=UserId}"/>
      <field name="Channel" layout="${mdc:item=Channel}"/>
      <field name="ApplicationName" layout="${gdc:item=ApplicationName}"/>
      <field name="LogDate" layout="${longdate}"/>
      <field name="MethodName" layout="${event-properties:item=MethodName}"/>
      <field name="ElapsedMilliseconds" layout="${event-properties:item=ElapsedMilliseconds}"/>
      <field name="ExternalServiceUrl" layout="${event-properties:item=ExternalServiceUrl}"/>
    </layout>
  </target>
  <rules>
     <logger name="*" minlevel="Debug" writeTo="Graylog" />
  </rules>
</nlog>
```

**Review by tomikiss — APPROVED** [review]

**Comment by tomikiss** [comment]
Thanks for this contribution, this has been merged and pushed to nuget.org today

**Comment by snakefoot** [comment]
@tomikiss Thank you for the quick response. Will try and get people to test it :)

**Comment by snakefoot** [comment]
@gokhanabatay [NLog.GelfLayout](https://www.nuget.org/packages/NLog.GelfLayout) ver. 0.4 have now been released with the ability to add extra fields (together with reduced memory allocations).

**Pull request merged**
