### PR TITLE
Updaterd NLog v4.7.15 + Newtonsoft.Json v13.0.1

### PR DESCRIPTION
**Pull request by snakefoot**
Dependency update before moving to NLog5

### CODE REVIEW

**Comment by snakefoot** [comment]
@tomikiss Ready for review and merge

**Comment by snakefoot** [comment]
@tomikiss Also possible to have it released to nuget ?

**Comment by tomikiss** [comment]
@snakefoot  this has been released now. Thank you for your contribution!

**Comment by snakefoot** [comment]
Excellent. Much appreciated.

**Pull request merged**
